// Code generated by "stringer -type FileFormat file_format.go"; DO NOT EDIT.

package tdGo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CSV-0]
	_ = x[TSV-1]
	_ = x[JSON-2]
	_ = x[MsgPack-3]
	_ = x[MsgPackGZ-4]
}

const _FileFormat_name = "CSVTSVJSONMsgPackMsgPackGZ"

var _FileFormat_index = [...]uint8{0, 3, 6, 10, 17, 26}

func (i FileFormat) String() string {
	if i < 0 || i >= FileFormat(len(_FileFormat_index)-1) {
		return "FileFormat(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FileFormat_name[_FileFormat_index[i]:_FileFormat_index[i+1]]
}
