// Code generated by "stringer -type JobStatus job_status.go"; DO NOT EDIT.

package tdGo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Running-0]
	_ = x[Error-1]
	_ = x[Queued-2]
	_ = x[Success-3]
	_ = x[All-4]
}

const _JobStatus_name = "RunningErrorQueuedSuccessAll"

var _JobStatus_index = [...]uint8{0, 7, 12, 18, 25, 28}

func (i JobStatus) String() string {
	if i < 0 || i >= JobStatus(len(_JobStatus_index)-1) {
		return "JobStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _JobStatus_name[_JobStatus_index[i]:_JobStatus_index[i+1]]
}
