// Code generated by "stringer -type JobType job_type.go"; DO NOT EDIT.

package tdGo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Presto-0]
	_ = x[Hive-1]
	_ = x[BulkLoad-2]
}

const _JobType_name = "PrestoHiveBulkLoad"

var _JobType_index = [...]uint8{0, 6, 10, 18}

func (i JobType) String() string {
	if i < 0 || i >= JobType(len(_JobType_index)-1) {
		return "JobType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _JobType_name[_JobType_index[i]:_JobType_index[i+1]]
}
